spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}f4683c14c6dc03775b75e9517499b68774298bb1772a43ecbeb77e64e0c48d21'

token:
  expiration_time: 86400000
  secret: '{cipher}AQAgHJYA7MuXBLa3DTt4VMGXnhLHBWbTNld52AeIfA9b5ogelMXde9eqJGB1nW9FsipVDJqbC9UyYWeYI2r/uQZQTGPeVlkzfN7fSzS68i2uvR+8vKmh7RpSAOIhJ+a94op4XPPoiIzkhSvNe/a6ZnwJJs1QNMxfjhOyGnvfj0sDSaQzNN98kwyvjb+gIdFpITarEDoOtAePZw6nWrjvTCBc0djnWpNLNI4iMOQrNP50H52897cdUul1wU4pqd2/6aSuuURXEzy9XmrQWs03EUiCNqN+wX5rcAr+N/rx9VMc0hS/+m/jUEnYzEwJ4bj8QAcbXYZcHGSLHoageQkxniWThf3sx8TcISzmrq68W/dayhgIyyX4cUa1nRO/lV4wlMq2ouAdMt6cl1vNQGyZCWF/'

gateway:
  ip: 192.168.0.87

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    order_is_empty: User's ordres is empty.