spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQBqEYV04IYu7aPFFhyi/EpJ3Xl36J0fIceM9ljMq+6qxoZRwvFFYHb07hYpqJNqxsafDeJXsb8caDERbyzND/Q5mslyQHH3QFxXU3ExfrkeTgXz5Hr8x6ac1OruU8LirQ467OTtqcxD07ZwCo8ErDa3kqmINYWPloG32RZpaKf07D5ie0vCY5+qf8RAZMhjsQfTqo4h26vqeQBM2DczjXZmjrh5cSFMmhPWFId0fSNGU7nnI3W0IKfcX/zG2oH7g6TWvC/60x6MTlA0h3u+BbeclWJn+XnGu2+6TDPnHbV4zj+mrxIn/BXbVHFN8QhL9UAwby+gTNnof5z3cTfJCaEKjf5u3VS1jl+mBkTVG8PJkkkrxziOvxGGE+G1bY9CwGs='

token:
  expiration_time: 86400000
  secret: '{cipher}AQAgHJYA7MuXBLa3DTt4VMGXnhLHBWbTNld52AeIfA9b5ogelMXde9eqJGB1nW9FsipVDJqbC9UyYWeYI2r/uQZQTGPeVlkzfN7fSzS68i2uvR+8vKmh7RpSAOIhJ+a94op4XPPoiIzkhSvNe/a6ZnwJJs1QNMxfjhOyGnvfj0sDSaQzNN98kwyvjb+gIdFpITarEDoOtAePZw6nWrjvTCBc0djnWpNLNI4iMOQrNP50H52897cdUul1wU4pqd2/6aSuuURXEzy9XmrQWs03EUiCNqN+wX5rcAr+N/rx9VMc0hS/+m/jUEnYzEwJ4bj8QAcbXYZcHGSLHoageQkxniWThf3sx8TcISzmrq68W/dayhgIyyX4cUa1nRO/lV4wlMq2ouAdMt6cl1vNQGyZCWF/'

gateway:
  ip: 172.18.0.5

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    order_is_empty: User's ordres is empty.